const knex = require("knex")({client:"sqlite3",connection:{filename:"/data/wiki.sqlite"},useNullAsDefault:true});
const crypto = require("crypto");

const now = new Date().toISOString();

const pages = [
  {
    path: "home",
    title: "Uliunai Platform Wiki",
    description: "Welcome page and project overview",
    content: [
      "# Uliunai Platform Wiki",
      "",
      "Welcome to the documentation for the **Uliunai.lt Killing Floor Community Platform**.",
      "",
      "## What is Uliunai?",
      "",
      "Uliunai is a Lithuanian Killing Floor gaming community platform. We run dedicated game servers and build web tools for server administration, live statistics, and community engagement.",
      "",
      "## Live URLs (Test Domains)",
      "",
      "| Service | URL |",
      "|---------|-----|",
      "| Hub (Landing Page) | [uliunai.fezle.io](https://uliunai.fezle.io) |",
      "| KF1 Website | [kf1-uliunai.fezle.io](https://kf1-uliunai.fezle.io) |",
      "| KF1 WebAdmin | [kf1-uliunai.fezle.io/webadmin/](https://kf1-uliunai.fezle.io/webadmin/) |",
      "| This Wiki | [wiki-uliunai.fezle.io](https://wiki-uliunai.fezle.io) |",
      "",
      "> These are temporary test domains. Final production domains will be under `*.uliunai.lt`.",
      "",
      "## Quick Navigation",
      "",
      "- [Getting Started](/en/getting-started) - Set up your development environment",
      "- [Architecture](/en/architecture) - System overview and infrastructure",
      "- [KF1 Apps](/en/kf1) - Website, WebAdmin, Mutator, Tools",
      "- [Deployment](/en/deployment) - CI/CD and manual deploy guides",
      "- [Design System](/en/design-system) - Colors, fonts, effects",
      "- [Troubleshooting](/en/troubleshooting) - Common issues and fixes",
      "",
      "## Project Status",
      "",
      "| Phase | Item | Status |",
      "|-------|------|--------|",
      "| 1 | Hub landing page | Done |",
      "| 2 | KF1 Website (React SPA) | Done (frontend) |",
      "| - | KF1 WebAdmin (Vue SPA) | Done |",
      "| - | UliunaiStats Mutator | Done |",
      "| - | Map Preview Tool | Done |",
      "| 3 | KF1 Statistics (PHP) | Not started |",
      "| 4 | VIP System (Stripe) | Not started |",
      "| 5 | KF2 Apps | Not started |",
      "",
      "## Repository",
      "",
      "Monorepo: `uliunai-platform` on GitHub",
      "",
      "```",
      "hub/                  - Hub landing page (vanilla HTML/CSS/JS)",
      "kf1/website/          - KF1 website (React 19 + Vite 7)",
      "kf1/webadmin/         - KF1 admin panel (Vue 3 + Vite 7)",
      "kf1/mutator/          - UliunaiStats server mutator (UnrealScript)",
      "kf1/tools/            - Python utilities (map preview extraction)",
      "kf1/statistics/       - KF1 stats page (Phase 3 - not started)",
      "kf2/                  - KF2 apps (future - empty)",
      "```"
    ].join("\n")
  },
  {
    path: "getting-started",
    title: "Getting Started",
    description: "Development environment setup guide",
    content: [
      "# Getting Started",
      "",
      "How to set up the Uliunai platform for local development.",
      "",
      "## Prerequisites",
      "",
      "- **Node.js 22+** (for website and webadmin)",
      "- **Python 3+** with Pillow (for map tools)",
      "- **Git**",
      "- **Caddy** (reverse proxy for subdomain simulation)",
      "",
      "## 1. Clone the Repository",
      "",
      "```bash",
      "git clone <repo-url> uliunai-platform",
      "cd uliunai-platform",
      "```",
      "",
      "## 2. Set Up Hosts File",
      "",
      "Add these entries to `C:\\Windows\\System32\\drivers\\etc\\hosts` (run as Administrator):",
      "",
      "```",
      "127.0.0.1   uliunai.lt",
      "127.0.0.1   kf1.uliunai.lt",
      "127.0.0.1   kf2.uliunai.lt",
      "```",
      "",
      "## 3. Install Dependencies",
      "",
      "```bash",
      "# KF1 Website",
      "cd kf1/website && npm install",
      "",
      "# KF1 WebAdmin",
      "cd ../webadmin && npm install",
      "```",
      "",
      "## 4. Start Development Servers",
      "",
      "Open 3 terminals:",
      "",
      "```bash",
      "# Terminal 1: KF1 Website (port 3000)",
      "cd kf1/website && npm run dev",
      "",
      "# Terminal 2: KF1 WebAdmin (port 3002)",
      "cd kf1/webadmin && npm run dev",
      "",
      "# Terminal 3: Caddy reverse proxy (from repo root)",
      "caddy run",
      "```",
      "",
      "## 5. Browse",
      "",
      "| URL | What |",
      "|-----|------|",
      "| http://uliunai.lt | Hub landing page |",
      "| http://kf1.uliunai.lt | KF1 website |",
      "| http://kf1.uliunai.lt:3002 | KF1 WebAdmin (direct) |",
      "",
      "## Build for Production",
      "",
      "```bash",
      "# KF1 Website",
      "cd kf1/website && npm run build    # -> dist/",
      "",
      "# KF1 WebAdmin",
      "cd kf1/webadmin && npm run build   # -> dist/",
      "```",
      "",
      "## Python Tools",
      "",
      "```bash",
      "pip install Pillow",
      "cd kf1/tools",
      "python extract_map_previews.py --help",
      "```"
    ].join("\n")
  },
  {
    path: "architecture",
    title: "Architecture Overview",
    description: "System architecture and infrastructure",
    content: [
      "# Architecture Overview",
      "",
      "## Infrastructure",
      "",
      "The platform runs on a **Hetzner dedicated server** with traffic routed through **Cloudflare Tunnel**.",
      "",
      "| Component | Details |",
      "|-----------|---------|",
      "| Server | Hetzner (94.130.51.236), Ubuntu 24.04, 16 CPU, 61GB RAM |",
      "| Ingress | Cloudflare Tunnel (SSL at edge, no certbot) |",
      "| Reverse Proxy | Caddy on localhost:8080 |",
      "| CI/CD | GitHub Actions -> rsync to server |",
      "",
      "## Port Allocation",
      "",
      "| Port | Service | Notes |",
      "|------|---------|-------|",
      "| 8075 | KF1 Game Server WebAdmin | Proxied via Caddy |",
      "| 8076 | Map Images API (Node.js) | systemd: `kf1-map-images` |",
      "| 8080 | Caddy (main reverse proxy) | systemd: `caddy-uliunai` |",
      "| 8082 | Wiki.js (Docker) | container: `uliunai-wiki` |",
      "",
      "> **Ports 80/443 belong to Fezle (nginx in Docker). NEVER touch.**",
      "",
      "## Traffic Flow",
      "",
      "```",
      "User -> Cloudflare (SSL) -> Tunnel -> Caddy (:8080) -> Service",
      "                                        |-- /           -> hub/ static files",
      "                                        |-- /webadmin/  -> kf1/webadmin/dist/",
      "                                        |-- /ServerAdmin/ -> localhost:8075 (KF1 server)",
      "                                        +-- /map-api/   -> localhost:8076 (Node.js API)",
      "```",
      "",
      "## Cloudflare Tunnel Config",
      "",
      "File: `/etc/cloudflared/config.yml`",
      "",
      "```yaml",
      "ingress:",
      "  - hostname: uliunai.fezle.io",
      "    service: http://localhost:8080",
      "  - hostname: kf1-uliunai.fezle.io",
      "    service: http://localhost:8080",
      "  - hostname: wiki-uliunai.fezle.io",
      "    service: http://localhost:8082",
      "  - service: http_status:404",
      "```",
      "",
      "## Key Directories on Server",
      "",
      "| Path | Contents |",
      "|------|----------|",
      "| /home/uliunai/hub/ | Hub static files |",
      "| /home/uliunai/kf1/website/dist/ | KF1 website build |",
      "| /home/uliunai/kf1/webadmin/dist/ | KF1 WebAdmin build |",
      "| /home/uliunai/kf1/map-images/ | Map images API + uploads |",
      "| /home/uliunai/wiki/ | Wiki.js Docker + data |",
      "| /home/uliunai/Caddyfile | Caddy routing config |",
      "",
      "## Systemd Services",
      "",
      "```bash",
      "systemctl status caddy-uliunai     # Main reverse proxy",
      "systemctl status kf1-map-images    # Map images API",
      "systemctl status kf1-server        # KF1 game server",
      "systemctl status cloudflared       # Cloudflare Tunnel",
      "```",
      "",
      "> **Always read `/root/SERVER_REGISTRY.md` on the server before making infrastructure changes.**"
    ].join("\n")
  },
  {
    path: "kf1",
    title: "KF1 Apps",
    description: "Killing Floor 1 applications overview",
    content: [
      "# KF1 Apps",
      "",
      "Everything related to Killing Floor 1 server management and community tools.",
      "",
      "## Applications",
      "",
      "| App | Tech | Status | Docs |",
      "|-----|------|--------|------|",
      "| [Website](/en/kf1/website) | React 19 + Vite 7 | Done | Full docs |",
      "| [WebAdmin](/en/kf1/webadmin) | Vue 3 + Vite 7 | Done | Full docs |",
      "| [Mutator](/en/kf1/mutator) | UnrealScript | Done | Full docs |",
      "| [Tools](/en/kf1/tools) | Python | Done | Full docs |",
      "| [Server](/en/kf1/server) | Dedicated Server | Running | Basic docs |",
      "| Statistics | PHP (planned) | Not started | - |",
      "",
      "## How It All Connects",
      "",
      "```",
      "KF1 Game Server",
      "  |-- UliunaiStats Mutator -> writes UliunaiStats.json every 2s",
      "  |-- Built-in WebAdmin (port 8075) -> HTML pages for server control",
      "  |",
      "  +-- Node.js API (port 8076)",
      "       |-- Reads UliunaiStats.json -> /map-api/game-state",
      "       |-- Serves map images -> /map-api/maps",
      "       +-- Syncs map rotation -> /map-api/sync-maplist",
      "",
      "KF1 Website (React)",
      "  +-- Polls /map-api/game-state for live stats display",
      "",
      "KF1 WebAdmin (Vue)",
      "  |-- Proxies /ServerAdmin/* -> game server WebAdmin",
      "  |-- Parses HTML responses -> typed TypeScript data",
      "  +-- Uses /map-api/* for map images + live stats",
      "```"
    ].join("\n")
  },
  {
    path: "kf1/website",
    title: "KF1 Website",
    description: "React SPA for the KF1 community website",
    content: [
      "# KF1 Website",
      "",
      "React single-page application for the Killing Floor 1 community.",
      "",
      "> **Screenshot TODO:** Add screenshot of the hero section and main page",
      "",
      "## Tech Stack",
      "",
      "| Technology | Version | Purpose |",
      "|------------|---------|---------|",
      "| React | 19.1 | UI framework |",
      "| TypeScript | 5.8 | Type safety |",
      "| Vite | 7.0 | Build tool, dev server on port 3000 |",
      "| Tailwind CSS | 3.4 | Utility-first styling |",
      "| React Router DOM | 7 | SPA routing |",
      "| i18next | 25.4 | Internationalization (ready, no translations yet) |",
      "| Vanta.js + Three.js | - | 3D fog background effect |",
      "| Lucide React | - | Icon library |",
      "",
      "## Commands",
      "",
      "```bash",
      "cd kf1/website",
      "npm install          # Install dependencies",
      "npm run dev          # Dev server at http://localhost:3000",
      "npm run build        # Production build -> dist/",
      "npm run preview      # Preview production build",
      "```",
      "",
      "## Project Structure",
      "",
      "```",
      "src/",
      "|-- components/",
      "|   |-- base/           # Button, Card (with variants)",
      "|   +-- feature/        # Navigation, Footer, LiveStats, VantaFog, AmbientEffects",
      "|-- hooks/              # useScrollReveal",
      "|-- pages/",
      "|   |-- home/",
      "|   |   |-- page.tsx    # Main landing page",
      "|   |   +-- components/ # HeroSection, AboutSection, ServerInfoSection,",
      "|   |                   # GallerySection, NewsSection, AdminSection,",
      "|   |                   # VipSection, ContactSection",
      "|   +-- NotFound.tsx    # 404 page",
      "|-- router/             # Route config (/ and 404)",
      "|-- i18n/               # Internationalization loader",
      "+-- index.css           # Global styles + 18 custom CSS effect categories",
      "```",
      "",
      "## Key Features",
      "",
      "- **Section-based navigation** - single page with smooth scroll to sections",
      "- **Live server stats** - polls `/map-api/game-state` for real-time player/wave info",
      "- **Horror theme** - glitch text, ember particles, scanlines, blood drip effects, Vanta.js fog",
      "- **Auto-imports** - React hooks, Router hooks, i18next available without explicit imports",
      "",
      "## Path Alias",
      "",
      "`@` -> `src/` (in both vite.config.ts and tsconfig.app.json)",
      "",
      "## Known Issues",
      "",
      "- IP address mismatch: HeroSection uses old IP `51.195.117.236:9980`, LiveStats uses current `94.130.51.236:7707`",
      "- ESLint installed but no config file or lint script",
      "- Readdy.ai widget in index.html has `PROJECT_ID_PLACEHOLDER`",
      "- Stripe, Supabase, Firebase installed but not yet used"
    ].join("\n")
  },
  {
    path: "kf1/webadmin",
    title: "KF1 WebAdmin",
    description: "Vue 3 SPA for KF1 server administration",
    content: [
      "# KF1 WebAdmin",
      "",
      "Modern Vue 3 single-page application that replaces the stock UE2 WebAdmin interface.",
      "",
      "> **Screenshot TODO:** Add screenshots of dashboard, map rotation, console, and players pages",
      "",
      "## Tech Stack",
      "",
      "| Technology | Version | Purpose |",
      "|------------|---------|---------|",
      "| Vue | 3.5 | UI framework (Composition API) |",
      "| TypeScript | 5.9 | Type safety |",
      "| Vite | 7.3 | Build tool, dev server on port 3002 |",
      "| Tailwind CSS | 3.4 | Utility-first styling |",
      "| Vue Router | 5 | SPA routing (base: `/webadmin/`) |",
      "| Pinia | 3 | State management |",
      "",
      "## Commands",
      "",
      "```bash",
      "cd kf1/webadmin",
      "npm install          # Install dependencies",
      "npm run dev          # Dev server at http://localhost:3002",
      "npm run build        # Type-check + production build -> dist/",
      "npm run preview      # Preview production build",
      "```",
      "",
      "## Pages (11 total)",
      "",
      "| Route | Page | Description |",
      "|-------|------|-------------|",
      "| `/overview` | OverviewPage | Dashboard with live stats, 5s auto-refresh |",
      "| `/players` | PlayersPage | Player list with kick/ban actions |",
      "| `/console` | ConsolePage | Server console, say/command modes, 2s auto-refresh |",
      "| `/mutators` | MutatorsPage | Mutator toggles and radio groups |",
      "| `/bots` | BotsPage | Bot enable/disable by category |",
      "| `/rules/:filter?` | RulesPage | Tabbed settings (Game/Chat/Voting/Sandbox/Server) |",
      "| `/maps` | MapsPage | Drag-and-drop map rotation editor with multi-select |",
      "| `/ip-policy` | IpPolicyPage | IP allow/deny rules |",
      "| `/voting-gameconfig` | VotingGameConfigPage | Game voting configurations |",
      "| `/map-images` | MapImagesPage | Map image upload/management grid |",
      "| `/game` | - | Redirects to `/overview` |",
      "",
      "## Architecture",
      "",
      "### Proxy Pattern",
      "",
      "```",
      "Browser -> Caddy (:8080)",
      "            |-- /webadmin/*       -> serves Vue SPA static files",
      "            |-- /ServerAdmin/*    -> proxies to KF1 game server (:8075)",
      "            +-- /map-api/*        -> proxies to Node.js API (:8076)",
      "```",
      "",
      "### HTML Parsing",
      "",
      "The stock KF1 WebAdmin returns raw HTML. Our `parsers.ts` (707 lines) extracts typed data:",
      "",
      "```",
      "fetchPage('current_players')  ->  raw HTML  ->  parsePlayers()  ->  PlayersData",
      "fetchPage('defaults_maps')    ->  raw HTML  ->  parseMaps()     ->  MapsData",
      "fetchPage('defaults_rules')   ->  raw HTML  ->  parseRules()    ->  RulesData",
      "```",
      "",
      "### Authentication",
      "",
      "HTTP Basic Auth. Credentials stored in `sessionStorage` (key: `kf1-webadmin-auth`), cleared on browser close.",
      "",
      "## Key Files",
      "",
      "| File | Purpose |",
      "|------|---------|",
      "| `src/services/api.ts` | HTTP client for UE2 WebAdmin + map API |",
      "| `src/services/parsers.ts` | HTML -> TypeScript parsers for all page types |",
      "| `src/stores/server.ts` | Pinia store (auth, current map/game type) |",
      "| `src/types/index.ts` | All TypeScript interfaces |",
      "",
      "## Advanced UI Features",
      "",
      "- **Drag-and-drop** map reordering with visual drop indicator",
      "- **Multi-select** with Ctrl+click (toggle) and Shift+click (range)",
      "- **Dual-list** map rotation editor (Not In Cycle <-> In Cycle)",
      "- **Terminal emulation** in console with command/say mode toggle",
      "- **Hover-overlay** upload interface for map images",
      "- **Tab-based** rule filtering by category"
    ].join("\n")
  },
  {
    path: "kf1/mutator",
    title: "UliunaiStats Mutator",
    description: "Server-side mutator that exports live game state to JSON",
    content: [
      "# UliunaiStats Mutator",
      "",
      "A custom **UnrealScript** server-side mutator for Killing Floor 1 that exports live game state to a JSON file every 2 seconds.",
      "",
      "## What It Does",
      "",
      "The mutator hooks into the KF1 game engine and writes a JSON file containing:",
      "- Wave progress (current/total, in progress, trader time)",
      "- Zed counts (alive, max simultaneous)",
      "- Difficulty level",
      "- Current map name",
      "- Per-player stats (name, perk, level, kills by monster type, cash, health, deaths, ping)",
      "",
      "## JSON Output Format",
      "",
      "File: `<KF_DIR>/UliunaiStats.json` (~1KB, written every 2 seconds)",
      "",
      "```json",
      "{",
      "  \"wave\": { \"current\": 3, \"total\": 10, \"inProgress\": true, \"traderTime\": false },",
      "  \"zeds\": { \"alive\": 12, \"maxAtOnce\": 16 },",
      "  \"difficulty\": \"Hard\",",
      "  \"difficultyNum\": 4,",
      "  \"map\": \"KF-BioticsLab\",",
      "  \"players\": [",
      "    {",
      "      \"name\": \"Player1\",",
      "      \"perk\": \"Berserker\",",
      "      \"perkLevel\": 6,",
      "      \"kills\": 45,",
      "      \"monsterKills\": { \"clot\": 20, \"gorefast\": 5, \"crawler\": 3, \"stalker\": 2, \"bloat\": 3, \"siren\": 2, \"husk\": 3, \"scrake\": 4, \"fleshpound\": 2, \"boss\": 1, \"other\": 0 },",
      "      \"cash\": 1500, \"health\": 100, \"maxHealth\": 100, \"deaths\": 0, \"ping\": 30",
      "    }",
      "  ],",
      "  \"playerCount\": 1",
      "}",
      "```",
      "",
      "## Files",
      "",
      "| File | Purpose |",
      "|------|---------|",
      "| `Classes/UliunaiStats.uc` | Main mutator class (JSON export, timer) |",
      "| `Classes/UliunaiStatsRules.uc` | Kill tracking (GameRules subclass) |",
      "| `UliunaiStats.u` | Compiled binary - deploy this |",
      "| `UliunaiStats.int` | Localization manifest |",
      "",
      "## Installation",
      "",
      "1. Copy `UliunaiStats.u` and `UliunaiStats.int` to server's `System/` directory",
      "2. Add to `KillingFloor.ini`: `ServerActors=UliunaiStats.UliunaiStats`",
      "3. **Do NOT use `?Mutator=` command line** - it doesn't persist across map changes",
      "4. Config auto-created: `UliunaiStats.ini` with `WriteInterval=2.0`",
      "",
      "## Compilation",
      "",
      "```bash",
      "# Source at: KillingFloor/UliunaiStats/Classes/*.uc",
      "cd \"D:/SteamLibrary/steamapps/common/KillingFloorBeta/System\"",
      "rm -f steam_appid.txt    # MUST delete or ucc.exe crashes",
      "# Comment out KFGui/GoodKarma/KFMutators EditPackages in KillingFloor.ini",
      "./ucc.exe make",
      "# Restore commented lines after compile",
      "```",
      "",
      "## Data Flow",
      "",
      "```",
      "KF1 Game Server",
      "  +-- UliunaiStats mutator (writes JSON every 2s)",
      "       +-- UliunaiStats.json on disk",
      "            +-- Node.js API reads it",
      "                 |-- /map-api/game-state -> KF1 Website (live stats)",
      "                 +-- /map-api/game-state -> KF1 WebAdmin (dashboard)",
      "```"
    ].join("\n")
  },
  {
    path: "kf1/tools",
    title: "KF1 Tools",
    description: "Python utilities for KF1 map management",
    content: [
      "# KF1 Tools",
      "",
      "Python utilities for working with Killing Floor 1 game files.",
      "",
      "## extract_map_previews.py",
      "",
      "Parses Unreal Engine 2 binary `.rom` map files and extracts embedded preview textures as PNG images.",
      "",
      "### Requirements",
      "",
      "```bash",
      "pip install Pillow",
      "```",
      "",
      "### Usage",
      "",
      "```bash",
      "# Extract all stock maps",
      "python extract_map_previews.py",
      "",
      "# Custom maps directory",
      "python extract_map_previews.py --maps-dir \"D:/MyMods/Maps\"",
      "",
      "# Single map extraction",
      "python extract_map_previews.py --file KF-Custom.rom",
      "",
      "# Discover texture names",
      "python extract_map_previews.py --file KF-Custom.rom --list-textures",
      "",
      "# Extract specific texture",
      "python extract_map_previews.py --file KF-Custom.rom --texture-name \"PreviewTex\"",
      "",
      "# Force re-extract",
      "python extract_map_previews.py --force",
      "```",
      "",
      "### Arguments",
      "",
      "| Argument | Description | Default |",
      "|----------|-------------|---------|",
      "| `--maps-dir` | Directory containing .rom files | KF Beta Maps dir |",
      "| `--output` | Output directory for PNGs | `./extracted_previews` |",
      "| `--file` | Extract single .rom file | - |",
      "| `--texture-name` | Exact texture name to extract | Auto-detect |",
      "| `--list-textures` | List all textures in a package | - |",
      "| `--force` | Overwrite existing PNGs | - |",
      "| `--no-overrides` | Skip built-in name overrides | - |",
      "",
      "### Supported Formats",
      "",
      "DXT1, DXT3, DXT5 (compressed) and RGBA8 (uncompressed).",
      "",
      "### Status",
      "",
      "18/19 stock maps extracted. KF-Menu (main menu, not playable) has no preview.",
      "",
      "### Upload to Server",
      "",
      "```bash",
      "scp kf1/tools/extracted_previews/*.png hetzner:/home/uliunai/kf1/map-images/uploads/",
      "```"
    ].join("\n")
  },
  {
    path: "kf1/server",
    title: "KF1 Server Management",
    description: "Managing the Killing Floor 1 dedicated server",
    content: [
      "# KF1 Server Management",
      "",
      "## Server Details",
      "",
      "| Property | Value |",
      "|----------|-------|",
      "| IP | 94.130.51.236 |",
      "| Game Port | 7707 |",
      "| WebAdmin Port | 8075 (proxied via Caddy) |",
      "| systemd Service | `kf1-server` |",
      "",
      "## Common Commands",
      "",
      "```bash",
      "ssh hetzner",
      "systemctl status kf1-server",
      "systemctl restart kf1-server",
      "systemctl stop kf1-server",
      "journalctl -u kf1-server -f",
      "```",
      "",
      "## Connecting",
      "",
      "### Direct Connect",
      "```",
      "steam://connect/94.130.51.236:7707",
      "```",
      "",
      "### Via Console",
      "Open KF1, press `~` (tilde), type:",
      "```",
      "open 94.130.51.236:7707",
      "```",
      "",
      "## Map Images API (port 8076)",
      "",
      "| Endpoint | Method | Description |",
      "|----------|--------|-------------|",
      "| `/map-api/maps` | GET | List all map images |",
      "| `/map-api/game-state` | GET | Live game state from mutator |",
      "| `/map-api/server-status` | GET | Server uptime + current map |",
      "| `/map-api/upload/:mapName` | POST | Upload map image |",
      "| `/map-api/upload/:mapName` | DELETE | Delete map image |",
      "| `/map-api/sync-maplist` | POST | Sync map rotation to .ini |",
      "| `/map-api/map-change` | POST | Report map change |",
      "",
      "Service: `systemctl restart kf1-map-images`",
      "",
      "## Server Quirks",
      "",
      "- **steam_appid.txt**: Must delete before `ucc.exe` or it crashes silently",
      "- **ServerActors vs Mutator**: Use `ServerActors=` in .ini (persists across map changes). Don't use `?Mutator=` on command line."
    ].join("\n")
  },
  {
    path: "deployment",
    title: "Deployment",
    description: "CI/CD pipeline and manual deployment guides",
    content: [
      "# Deployment",
      "",
      "## CI/CD Pipeline (GitHub Actions)",
      "",
      "**Trigger:** Push to `master` branch",
      "**File:** `.github/workflows/deploy.yml`",
      "",
      "### Steps",
      "",
      "1. Builds KF1 Website (`npm ci && npm run build`)",
      "2. Builds KF1 WebAdmin (`npm ci && npm run build`)",
      "3. Rsyncs to Hetzner `/home/uliunai/`",
      "",
      "### Required Secrets",
      "",
      "| Secret | Description |",
      "|--------|-------------|",
      "| `DEPLOY_SSH_KEY` | SSH private key for Hetzner |",
      "| `DEPLOY_HOST` | Server IP (94.130.51.236) |",
      "| `DEPLOY_USER` | SSH user |",
      "",
      "## Manual Deploy (SCP)",
      "",
      "> **CRITICAL: Deploy to the right directory!** Caddy serves from `dist/`, not the parent.",
      "",
      "```bash",
      "# KF1 Website",
      "cd kf1/website && npm run build",
      "scp -r dist/* hetzner:/home/uliunai/kf1/website/dist/",
      "",
      "# KF1 WebAdmin",
      "cd kf1/webadmin && npm run build",
      "scp -r dist/* hetzner:/home/uliunai/kf1/webadmin/dist/",
      "",
      "# Hub (static, no build)",
      "scp -r hub/* hetzner:/home/uliunai/hub/",
      "",
      "# Mutator binary",
      "scp kf1/mutator/UliunaiStats.u hetzner:/home/uliunai/kf-server/System/",
      "```",
      "",
      "## Caddy Configuration",
      "",
      "**Config:** `/home/uliunai/Caddyfile`",
      "**Service:** `caddy-uliunai` (NOT `caddy`)",
      "",
      "```bash",
      "systemctl reload caddy-uliunai    # Reload config",
      "systemctl status caddy-uliunai    # Check status",
      "```",
      "",
      "## After Deploying",
      "",
      "No restart needed for static file changes.",
      "",
      "For service changes:",
      "```bash",
      "systemctl restart kf1-map-images    # Map images API",
      "systemctl restart kf1-server        # Game server",
      "systemctl reload caddy-uliunai      # Caddy routing changes",
      "systemctl restart cloudflared       # Tunnel changes (brief interruption!)",
      "```"
    ].join("\n")
  },
  {
    path: "design-system",
    title: "Design System",
    description: "Visual identity - colors, fonts, effects, Tailwind tokens",
    content: [
      "# Design System",
      "",
      "All Uliunai subdomains share the same **horror/gaming** visual identity.",
      "",
      "> Full reference: `DESIGN_SYSTEM.md` in the repository root.",
      "",
      "## Fonts",
      "",
      "| Font | Usage | Weight |",
      "|------|-------|--------|",
      "| **Orbitron** | Headings, titles | 400, 700, 900 |",
      "| **Rajdhani** | Body text, UI | 400, 600, 700 |",
      "",
      "Loaded via Google Fonts CDN.",
      "",
      "## Color Palette",
      "",
      "| Token | Hex | Usage |",
      "|-------|-----|-------|",
      "| `blood-red` | `#8B0000` | Primary accent, gradients |",
      "| `dark-red` | `#4A0000` | Gradient endpoints |",
      "| bright red | `#dc2626` | Buttons, highlights, scrollbar |",
      "| `horror-gray` | `#1a1a1a` | Surface/card backgrounds |",
      "| black | `#000000` | Page backgrounds |",
      "",
      "## Tailwind Tokens",
      "",
      "```javascript",
      "// Colors",
      "'blood-red': '#8B0000',",
      "'dark-red': '#4A0000',",
      "'horror-gray': '#1a1a1a',",
      "",
      "// Shadows",
      "'red-glow': '0 0 20px rgba(220, 38, 38, 0.3)',",
      "'blood': '0 4px 20px rgba(139, 0, 0, 0.4)',",
      "",
      "// Animations",
      "'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',",
      "'bounce-slow': 'bounce 2s infinite',",
      "```",
      "",
      "## CSS Effects (18+ categories)",
      "",
      "| Effect | Description |",
      "|--------|-------------|",
      "| Glitch text | RGB chromatic aberration |",
      "| Scanlines | CRT overlay with moving red line |",
      "| Blood drip | Pseudo-element gradient drips |",
      "| Floating embers | 35 rising particles with sway |",
      "| Vignette | Radial dark edges |",
      "| Flicker | Irregular opacity animation |",
      "| Fog drift | Slow translateX/Y movement |",
      "| Scroll reveal | Fade-in with directional movement |",
      "| Horror card hover | Glow + lift on hover |",
      "| VHS/static noise | Animated grid overlay |",
      "| Pulsing glow | CTA button breathing effect |",
      "| Screen flicker | Rare full-screen red flash |",
      "",
      "## Icons",
      "",
      "| Library | Version | Source |",
      "|---------|---------|--------|",
      "| Remix Icon | 4.5.0 | CDN |",
      "| Font Awesome | 6.4.0 | CDN |",
      "| Lucide React | latest | npm (website only) |",
      "| Motion Icons React | latest | npm (website only) |"
    ].join("\n")
  },
  {
    path: "troubleshooting",
    title: "Troubleshooting",
    description: "Common issues and their solutions",
    content: [
      "# Troubleshooting",
      "",
      "## KF1 Server",
      "",
      "### ucc.exe crashes silently during compilation",
      "**Cause:** `steam_appid.txt` exists in System directory.",
      "**Fix:**",
      "```bash",
      "rm -f steam_appid.txt",
      "./ucc.exe make",
      "```",
      "",
      "### Mutator doesn't persist across map changes",
      "**Cause:** Using `?Mutator=` on command line.",
      "**Fix:** Use `ServerActors=` in `KillingFloor.ini`:",
      "```ini",
      "ServerActors=UliunaiStats.UliunaiStats",
      "```",
      "",
      "### EditPackages errors during compilation",
      "**Cause:** KFGui, GoodKarma, KFMutators don't have source available.",
      "**Fix:** Comment these in KillingFloor.ini before compiling, restore after.",
      "",
      "## Website",
      "",
      "### IP address mismatch in live stats",
      "HeroSection shows `51.195.117.236:9980` (old), LiveStats shows `94.130.51.236:7707` (current).",
      "**Fix:** Update old IP references in HeroSection.tsx and ServerInfoSection.tsx.",
      "",
      "### Readdy.ai widget not loading",
      "`PROJECT_ID_PLACEHOLDER` in index.html. Replace with actual ID or remove widget.",
      "",
      "## Deployment",
      "",
      "### Changes not showing after deploy",
      "1. Deployed to wrong directory? Caddy serves from `dist/`",
      "2. Clear browser cache (Ctrl+Shift+R)",
      "3. Check: `systemctl status caddy-uliunai`",
      "",
      "### Caddy not reloading",
      "Use `systemctl reload caddy-uliunai` (NOT `caddy`)",
      "",
      "### Cloudflare Tunnel down",
      "```bash",
      "systemctl status cloudflared",
      "systemctl restart cloudflared    # Brief interruption to ALL tunneled sites!",
      "journalctl -u cloudflared -f",
      "```",
      "",
      "## Wiki.js",
      "",
      "### Forgot admin password",
      "```bash",
      "ssh hetzner",
      "docker exec uliunai-wiki node -e \"",
      "const bcrypt = require('bcryptjs-then');",
      "const knex = require('knex')({client:'sqlite3',connection:{filename:'/data/wiki.sqlite'},useNullAsDefault:true});",
      "bcrypt.hash('NEW_PASSWORD').then(async h => {",
      "  await knex('users').where({id:1}).update({password:h});",
      "  console.log('Done');",
      "  await knex.destroy();",
      "});",
      "\"",
      "```",
      "",
      "### Container won't start",
      "```bash",
      "cd /home/uliunai/wiki",
      "docker compose logs -f",
      "chmod 777 /home/uliunai/wiki/data    # Fix permissions",
      "docker compose restart",
      "```",
      "",
      "## Domain Migration",
      "",
      "When `uliunai.lt` is purchased, update:",
      "1. Cloudflare Tunnel ingress (`/etc/cloudflared/config.yml`)",
      "2. Hub CTA links (`hub/index.html`)",
      "3. Website nav links (`kf1/website/`)",
      "4. WebAdmin sidebar links (`kf1/webadmin/`)",
      "5. Wiki.js site URL (Admin > General)",
      "6. See `/home/uliunai/DOMAIN_MIGRATION.md` on the server"
    ].join("\n")
  }
];

async function populate() {
  for (const page of pages) {
    const hash = crypto.createHash("sha256").update("en|" + page.path).digest("hex");

    const existing = await knex("pages").where({path: page.path, localeCode: "en"}).first();
    if (existing) {
      console.log("Skipping (exists):", page.path);
      continue;
    }

    const result = await knex("pages").insert({
      path: page.path,
      hash: hash,
      title: page.title,
      description: page.description,
      isPrivate: false,
      isPublished: true,
      privateNS: "",
      publishStartDate: "",
      publishEndDate: "",
      content: page.content,
      render: page.content,
      toc: "[]",
      contentType: "markdown",
      createdAt: now,
      updatedAt: now,
      editorKey: "markdown",
      localeCode: "en",
      authorId: 1,
      creatorId: 1,
      extra: "{}"
    });

    const pageId = result[0] || result;
    const parts = page.path.split("/");
    let parentId = null;
    if (parts.length > 1) {
      const parentPath = parts.slice(0, -1).join("/");
      const parent = await knex("pageTree").where({path: parentPath, localeCode: "en"}).first();
      if (parent) parentId = parent.id;
    }

    await knex("pageTree").insert({
      path: page.path,
      depth: parts.length,
      title: page.title,
      isPrivate: false,
      isFolder: false,
      privateNS: "",
      parent: parentId,
      pageId: pageId,
      localeCode: "en",
      ancestors: JSON.stringify(parts.slice(0, -1))
    });

    console.log("Created:", page.path, "(id:" + pageId + ")");
  }

  await knex.destroy();
  console.log("\nDone! All pages created.");
}

populate().catch(e => { console.error(e); process.exit(1); });
